name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-unit-tests:
    name: "Build and unit tests"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17
      - name: Cache sbt
        uses: coursier/cache-action@v6.4
      - name: Compile and test
        run: sbt compile test
